apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-api-messaging
data:
  DATABASE_URL: "Server=db;Port=5432;Database=tech_challenge;User Id=admin;Password=admin;"
  API_KEY: "api-key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-messaging-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-api-messaging
  template:
    metadata:
      labels:
        app: tech-challenge-api-messaging
    spec:
      containers:
        - name: apiqueue
          image: ciroa/tech-challenge-group43:Techchallenge01.ApiMessaging-latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__postgres
              value: "Server=tech-challenge-postgres-service;Port=5432;Database=tech_challenge;User Id=admin;Password=admin;"
          envFrom:
            - configMapRef:
                name: tech-challenge-api-messaging

---s
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-messaging-service
spec:
  selector:
    app: tech-challenge-api-messaging
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
