apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  API_SERVICE_URL: "http://tech-challenge-api-service:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-api-gateway
  template:
    metadata:
      labels:
        app: tech-challenge-api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: ciroa/tech-challenge-group43:TechChallenge01.ApiGateway-latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-gateway-service
spec:
  selector:
    app: tech-challenge-api-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort
