apiVersion: v1
kind: ConfigMap
metadata:
  name: api-token-config
data:
  DATABASE_URL: "mongodb://tech-challenge-db:27017"
  API_KEY: "api-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-token-config
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-token-config
  template:
    metadata:
      labels:
        app: api-token-config
    spec:
      containers:
        - name: tokenapi
          image: ciroa/tech-challenge-group43:TechChallenge01.TokenApi-latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-token-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-token-config-service
spec:
  selector:
    app: api-token-config
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
