apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DATABASE_URL: "mongodb://tech-challenge-db:27017"
  API_KEY: "api-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-api
  template:
    metadata:
      labels:
        app: tech-challenge-api
    spec:
      containers:
        - name: api-container
          image: ciroa/tech-challenge-group43:TechChallenge01.Api-latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-service
spec:
  selector:
    app: tech-challenge-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
