apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'apiqueue01-read-prometheus'
        static_configs:
          - targets: ['tech-challenge-api-messaging-service:8080']
      
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq:15692']
      
      - job_name: 'tokenapi-read-prometheus'
        static_configs:
          - targets: ['api-token-config-service:8080']