name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'liciomachado'
          password: ${{ secrets.SECRET_DOCKERHUB }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./src/TechChallenge01.Api/Dockerfile .
          tags: 'latest'
          push: true
          
