name: Build, Test and Deploy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    strategy:
      matrix:
        service: [TechChallenge01.Api, TechChallenge01.TokenApi, TechChallenge01.ApiGateway, TechChallenge01.Infra.Consumer,Techchallenge01.ApiMessaging]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore, Build and Test
        run: |
          dotnet restore ./TechChallenge01.sln
          dotnet build ./TechChallenge01.sln --configuration Release --no-restore
          dotnet test ./TechChallenge01.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/${{ matrix.service }}/Dockerfile
          tags:  ${{ env.DOCKERHUB_USERNAME }}/tech-challenge-group43:${{ matrix.service }}-latest
          push: true


  build_postgres:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push PostgreSQL image
        uses: docker/build-push-action@v6
        with:
          context: ./Configs
          file: Dockerfile.postgres
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/tech-challenge-postgres:latest
