name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install globalization libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8
        sudo update-locale LANG=en_US.UTF-8
        
    - name: Restore
      run: dotnet restore ./TechChallenge01.sln
      
    - name: Build
      run: dotnet build ./TechChallenge01.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ./TechChallenge01.sln --configuration Release --no-restore --no-build
